name: Create Release on Push

permissions:
  contents: write

on:
  push:
    branches:
      - master
      - version/1.1.0

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set release tag name
        id: tag
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          if [ "$BRANCH_NAME" == "master" ]; then
            TAG_NAME="latest"
          else
            TAG_NAME="${BRANCH_NAME##*/}"
          fi
          echo "tag_name=$TAG_NAME-$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag_name }}
          name: Release ${{ steps.tag.outputs.tag_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
